conky.config = {
    -- Backend
    out_to_x = false,
    out_to_wayland = true,

    -- Niri usa layer-shell: 'desktop' o 'normal' non serve,
    -- il backend Wayland ignora own_window_type e usa layer-shell direttamente
    own_window = true,
    own_window_type = 'normal',      -- ignorato dal backend Wayland
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    -- Trasparenza ARGB
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 195,
    own_window_colour = '#1a1b26',

    -- Layout
    alignment = 'top_right',
    gap_x = 40,
    gap_y = 60,
    minimum_width = 320,
    minimum_height = 250,

    -- Performance
    update_interval = 1,
    double_buffer = true,

    -- Font
    use_xft = true,
    font = 'JetBrainsMono Nerd Font:size=10',

    -- Colori (Tokyo Night)
    default_color = '#a9b1d6',
    color1 = '#f7768e',
    color2 = '#bb9af7',
    color3 = '#7dcfff',
    color4 = '#9ece6a',
};

conky.text = [[
# UPTIME
${color3}󱎫 Uptime:${color} ${alignr}${uptime_short}

# CPU
${color2} CPU${color} ${alignr}${cpu cpu0}%
${color1}${cpubar cpu1 6,70} ${cpubar cpu2 6,70} ${cpubar cpu3 6,70} ${cpubar cpu4 6,70}${color}

# RAM
${color2} RAM${color} ${mem} / ${memmax} ${alignr}${memperc}%
${color1}${membar 8}${color}

# RETE
${color3}󰹹 NETWORK:${color}
 ${downspeed wlp4s0} ${alignr} ${upspeed wlp4s0}

# DISCO
${color4}󰋊 STORAGE${color} ${alignr}${fs_used /} / ${fs_size /}
${color4}${fs_bar 8 /}${color}
]];
